import React from "react";

const ProductId = async ({ params }) => {
  const { productId } = await params;

  return <div>ProductId {productId}</div>;
};

export const generateMetadata = ({ params }) => {
  const { productId } = params;

  return {
    title: `id is${productId}`,
    description: "Generated by create next app",
  };
};

export default ProductId;
